services:
  app:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data
    depends_on:
      - db
    command: python -m src.cli run-all

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: fx
      POSTGRES_USER: fx_user
      POSTGRES_PASSWORD: fx_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  dashboard:
    build: .
    env_file: .env
    entrypoint: ""  # garante que não vai rodar o cli.py
    command: streamlit run src/dashboard/app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./data:/app/data
      - ./.streamlit:/home/appuser/.streamlit:ro
      - ./.streamlit:/app/.streamlit:ro
    ports:
      - "8501:8501"
    depends_on:
      - app

volumes:
  pgdata:
